services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass4Kien!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  ocelotgateway:
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - authservice
      - urlservice
      - qrservice
    networks:
      - backend

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5001:80"
    networks:
      - backend

  urlservice:
    build:
      context: .
      dockerfile: URLService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - redis
    networks:
      - backend

  qrservice:
    build:
      context: .
      dockerfile: QRService/Dockerfile
    ports:
      - "5003:80"
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - ocelotgateway
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data: